# Generated by Django 4.0.6 on 2022-07-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_complaints_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='advancepayment',
            field=models.CharField(default='20', max_length=10),
            preserve_default=False,
        ),
    ]
