# Generated by Django 4.0.6 on 2022-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_vehicleentry_advancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='finalpay',
            field=models.CharField(default='8', max_length=10),
            preserve_default=False,
        ),
    ]
