# Generated by Django 4.0.6 on 2022-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_vehicleentry_finalpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleentry',
            name='finalpay',
        ),
        migrations.AddField(
            model_name='vehicleexit',
            name='finalpay',
            field=models.CharField(default='10', max_length=10),
            preserve_default=False,
        ),
    ]
