# Generated by Django 4.0.6 on 2022-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_remove_vehicleentry_finalpay_vehicleexit_finalpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
